version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-patients
    environment:
      SA_PASSWORD: "Container123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./sql:/docker-entrypoint-initdb.d

  api:   
    build:
      context: ./PatientsBackend
      dockerfile: Dockerfile
    container_name: api-patients
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=bdPatient;User Id=sa;Password=Container123!;TrustServerCertificate=True;"
    depends_on:
      - db

volumes:
  sqlserverdata:
