version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-patients
    environment:
      SA_PASSWORD: "Container123!"   
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  

  api:
    build:
      context: ./PatientsBackend   
      dockerfile: Dockerfile
    container_name: api-patients
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=bdPatient;User Id=sa;Password=container123;TrustServerCertificate=True;"
    depends_on:
      - db
